package com.greenreach.features.location.model;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;

/**
 * Base class for any location component (Room, Zone, Rack, Level, Slot)
 * that has an autogenerated ID and a unique code.
 *
 * @author Ava Birtwistle
 * @version 1.0
 * @since 2025-06-24
 */
@MappedSuperclass
public abstract class Locatable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", updatable = false, nullable = false)
    private Long id;

    @Column(name = "code", nullable = false, unique = true)
    private String code;

    protected Locatable() {
    }

    protected Locatable(String code) {
        this.code = code;
    }

    public Long getId() {
        return id;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }
}
